name: Publish Package
on:
  push:
    branches:
      - main
jobs:
  sanity-check:
    uses: yoerinijs/phishing-detection-plugin/.github/workflows/sanity_check.yml@main

  Release:
    runs-on: ubuntu-latest
    needs: sanity-check
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: setup
        run: |
          npm install
          npm run build

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: increment version
        id: increment_version
        run: |
          CURRENT_VERSION=$(jq -r .version package.json)
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$NF += 1; print}')
          jq --arg version "$NEW_VERSION" '.version = $version' package.json > tmp.json && mv tmp.json package.json
          git add --force package.json
          git commit -m "chore(package.json): bump version to $NEW_VERSION" --no-verify
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: update manifest.json
        run: |
          export CI_MODE=true
          jq --arg version "$NEW_VERSION" '.version = $version' src/browsers/_shared/manifest.json > src/browsers/_shared/tmp.json && mv src/browsers/_shared/tmp.json src/browsers/_shared/manifest.json
          git add --force src/browsers/_shared/manifest.json

      - name: create release
        run: |
          sh ./.github/create_release.sh

      - name: commit release
        run: |
          export CI_MODE=true
          git add --force release/
          git commit -m "build(extension): release '$NEW_VERSION'" --no-verify
          git push origin main --no-verify
          git tag -a "$NEW_VERSION" -m "Release $NEW_VERSION"
          git push --tags --no-verify