name: Publish Package
on:
  push:
    branches:
      - main
jobs:
  sanity-check:
    uses: yoerinijs/phishing-detection-plugin/.github/workflows/sanity_check.yml@main

  Release:
    runs-on: ubuntu-latest
    needs: sanity-check
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: setup
        run: |
          npm install
          npm run build

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: get new version
        id: get_version
        run: |
          export CI_MODE=true
          NEW_FRAMEWORK_VERSION=$(cat package.json \
            | grep version \
            | head -1 \
            | awk -F: '{ print $2 }' \
            | sed 's/[",]//g' \
            | tr -d '[[:space:]]')
          echo "NEW_VERSION=$NEW_FRAMEWORK_VERSION" >> $GITHUB_ENV
          git add --force package.json

      - name: update manifest.json
        run: |
          export CI_MODE=true
          jq --arg version "$NEW_VERSION" '.version = $version' src/browsers/_shared/manifest.json > src/browsers/_shared/tmp.json && mv src/browsers/_shared/tmp.json src/browsers/_shared/manifest.json
          git add --force src/browsers/_shared/manifest.json

      - name: create release
        run: |
          sh ./.github/create_release.sh

      - name: commit
        run: |
          export CI_MODE=true
          git add --force release/
          git commit -m "build(extension): release '$NEW_VERSION'" --no-verify
          git push origin main --no-verify
          git tag -a "$NEW_VERSION" -m "Release $NEW_VERSION"
          git push --tags --no-verify
